#!/bin/bash

if [ "$EUID" -ne 0 ]
    then echo "Please run this as root"
    exit

    else echo "Root User Detected"
fi

# Remove keys
echo Removing Keys
rm -v /etc/ssh/ssh_host_*

echo
echo
#Regenerate the keys
echo Regenerating the Keys
dpkg-reconfigure openssh-server

echo
echo
#Restart SSH
echo Restarting SSH Server
systemctl restart ssh
